### ISSUE TITLE
LGPL may not be AppStore-friendly

### ISSUE THREAD

**Issue by horaceho** [lnafziger/Numberpad#1]
[LGPL may not be AppStore-friendly](http://stackoverflow.com/questions/459833/which-open-source-licenses-are-compatible-with-the-iphone-and-app-store). Any chance to release the code under a more liberated license?

**Comment by lnafziger** [comment]
Yeah, I found that out after I put it there.

I will be re-releasing it under the MIT license as soon as I finish up another project that I am working on.

Please feel free to use it now though and I release the rights per the MIT license to anybody who wants to copy it now (without being bound to the LGPL).

If you want to fork it and change the license for me, I'll be happy to accept that though.  :-)

**Comment by horaceho** [comment]
Thank you!

**Comment by lnafziger** [comment]
Updated to v0.9.3 which changes the license to the MIT license, along with other changes.
