### ISSUE TITLE
Fail to link to LNNumberPad

### ISSUE THREAD

**Issue by felixriestra** [lnafziger/Numberpad#4]
Hello
I followed the instructions to get this in my project.
Add the 3 files in the project as show below.
![lnadded](https://f.cloud.github.com/assets/4650316/628183/cdbd683e-d087-11e2-8eeb-b625915d9a39.png)

I import the header and create a "user" text field, synthesize and set delegate to the ViewController.
# import "LNNumberpad.h"

@synthesize user;

.........
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  
  self.user.inputView   = [LNNumberpad defaultLNNumberpad];
  ...........

When I build, got the following message:

Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_LNNumberpad", referenced from:
      objc-class-ref in VoltageDropViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It look that the compiler do not see the class LNNumberPad....
My project is using ARC.

**Comment by lnafziger** [comment]
It looks like you did not add the files to your target app when you added them.

Make sure while adding the files that you select the checkmark next to your app in the `Add to targets` box under the file picker.

You can also go to the `Build Phases` section under the `Targets` section of the project settings and make sure that `LNNumberpad.m` is listed under `Compile Sources` and `LNNumberpad.xib` is listed under `Copy Bundle Resources`.
