### ISSUE TITLE
Max Char Limit

### ISSUE THREAD

**Issue by ghost** [lnafziger/Numberpad#5]
Great work Louis, your keypad solve all my problems with wrong chars sent from my app to my ERP, I want to ask about the implementation of max char limit inside the keypad, how you do that, it is possible? I try with different ways but i only way i can do this is implement this in my code, don't inside de keypad itself :(
Sorry about my English.

**Comment by lnafziger** [comment]
Hi JRaviles,

Thank you for the comments, however I want my keyboard to replicate the standard iOS keyboards as closely as possible so do not want to implement this feature.  As you stated, doing this in your code (using the text field delegates) is generally the way that this is done.
